import LeanNPHardness.MachineEmbedding
import LeanNPHardness.MachineControl
import LeanNPHardness.MachineControlSimulation
import LeanNPHardness.MachineCompositionProgram
import LeanNPHardness.MachineTransfer
import LeanNPHardness.PolytimeComposition

namespace LeanNPHardness.Audit

open Computability

#print axioms LeanNPHardness.ManyOneReduction.comp
#print axioms LeanNPHardness.PolytimeManyOneReduction.refl
#print axioms LeanNPHardness.PolytimeManyOneReduction.compOfWitness
#print axioms LeanNPHardness.PolytimeManyOneReduction.reflComp
#print axioms LeanNPHardness.PolytimeManyOneReduction.compRefl
#print axioms LeanNPHardness.MachineComposition.liftLeft_step
#print axioms LeanNPHardness.MachineComposition.liftRight_step
#print axioms LeanNPHardness.MachineComposition.middleAlphabetEquiv_symm_apply_apply
#print axioms LeanNPHardness.MachineComposition.liftLeftControl_step
#print axioms LeanNPHardness.MachineComposition.liftLeftThenTransfer_step
#print axioms LeanNPHardness.MachineComposition.liftLeftThenTransfer_step_of_halt
#print axioms LeanNPHardness.MachineComposition.liftRightControl_step
#print axioms LeanNPHardness.MachineComposition.transferLabel_ne_fillInputLabel
#print axioms LeanNPHardness.MachineComposition.transferLeftStacks_update
#print axioms LeanNPHardness.MachineComposition.transferRightStacks_update
#print axioms LeanNPHardness.MachineComposition.liftScratch_step
#print axioms LeanNPHardness.MachineComposition.reverseOutput_iteration_nonempty
#print axioms LeanNPHardness.MachineComposition.reverseOutput_iteration_empty
#print axioms LeanNPHardness.MachineComposition.reverseOutput_whole_list
#print axioms LeanNPHardness.MachineComposition.fillInput_iteration_nonempty
#print axioms LeanNPHardness.MachineComposition.fillInput_iteration_empty
#print axioms LeanNPHardness.MachineComposition.fillInput_whole_list
#print axioms LeanNPHardness.MachineComposition.transfer_whole_list
#print axioms LeanNPHardness.MachineComposition.compositionAux
#print axioms LeanNPHardness.MachineComposition.compositionProgram_left_step
#print axioms LeanNPHardness.MachineComposition.compositionProgram_right_step
#print axioms LeanNPHardness.MachineComposition.compositionProgram_transfer_step
#print axioms LeanNPHardness.MachineComposition.compositionProgram_reverseOutput_whole_list
#print axioms LeanNPHardness.MachineComposition.compositionProgram_fillInput_whole_list
#print axioms LeanNPHardness.MachineComposition.compositionProgram_transfer_whole_list

end LeanNPHardness.Audit
