import LeanNPHardness.MachineEmbedding
import LeanNPHardness.MachineCompositionRuntime
import LeanNPHardness.MachineRuntimeBounds
import LeanNPHardness.MachineControl
import LeanNPHardness.MachineControlSimulation
import LeanNPHardness.MachineCompositionExecution
import LeanNPHardness.MachineCompositionProgram
import LeanNPHardness.MachineTransfer
import LeanNPHardness.PairEncoding
import LeanNPHardness.PairMachine
import LeanNPHardness.PolytimeComposition
import LeanNPHardness.ComplexityClasses

namespace LeanNPHardness.Audit

open Computability

#print axioms LeanNPHardness.ManyOneReduction.comp
#print axioms LeanNPHardness.PolytimeManyOneReduction.refl
#print axioms LeanNPHardness.PolytimeManyOneReduction.compOfWitness
#print axioms LeanNPHardness.PolytimeManyOneReduction.reflComp
#print axioms LeanNPHardness.PolytimeManyOneReduction.compRefl
#print axioms LeanNPHardness.MachineComposition.liftLeft_step
#print axioms LeanNPHardness.MachineComposition.liftRight_step
#print axioms LeanNPHardness.MachineComposition.middleAlphabetEquiv_symm_apply_apply
#print axioms LeanNPHardness.MachineComposition.liftLeftControl_step
#print axioms LeanNPHardness.MachineComposition.liftLeftThenTransfer_step
#print axioms LeanNPHardness.MachineComposition.liftLeftThenTransfer_step_of_halt
#print axioms LeanNPHardness.MachineComposition.liftRightControl_step
#print axioms LeanNPHardness.MachineComposition.liftRightThenHalt_stepAux
#print axioms LeanNPHardness.MachineComposition.transferLabel_ne_fillInputLabel
#print axioms LeanNPHardness.MachineComposition.transferLeftStacks_update
#print axioms LeanNPHardness.MachineComposition.transferRightStacks_update
#print axioms LeanNPHardness.MachineComposition.liftScratch_step
#print axioms LeanNPHardness.MachineComposition.reverseOutput_iteration_nonempty
#print axioms LeanNPHardness.MachineComposition.reverseOutput_iteration_empty
#print axioms LeanNPHardness.MachineComposition.reverseOutput_whole_list
#print axioms LeanNPHardness.MachineComposition.fillInput_iteration_nonempty
#print axioms LeanNPHardness.MachineComposition.fillInput_iteration_empty
#print axioms LeanNPHardness.MachineComposition.fillInput_whole_list
#print axioms LeanNPHardness.MachineComposition.transfer_whole_list
#print axioms LeanNPHardness.MachineComposition.compositionAux
#print axioms LeanNPHardness.MachineComposition.compositionProgram_left_step
#print axioms LeanNPHardness.MachineComposition.compositionProgram_right_step
#print axioms LeanNPHardness.MachineComposition.compositionProgram_transfer_step
#print axioms LeanNPHardness.MachineComposition.compositionProgram_reverseOutput_whole_list
#print axioms LeanNPHardness.MachineComposition.compositionProgram_fillInput_whole_list
#print axioms LeanNPHardness.MachineComposition.compositionProgram_transfer_whole_list
#print axioms LeanNPHardness.MachineComposition.compositionProgram_left_run
#print axioms LeanNPHardness.MachineComposition.compositionProgram_left_run_to_transfer
#print axioms LeanNPHardness.MachineComposition.compositionProgram_left_evalsTo_transfer
#print axioms LeanNPHardness.MachineComposition.rightPhaseStacks_update
#print axioms LeanNPHardness.MachineComposition.compositionProgram_right_step_preserving_left
#print axioms LeanNPHardness.MachineComposition.compositionProgram_right_run
#print axioms LeanNPHardness.MachineComposition.compositionProgram_right_evalsTo
#print axioms LeanNPHardness.MachineComposition.rightEntryCfg_eq_rightPhaseCfg
#print axioms LeanNPHardness.MachineComposition.compositionProgram_rightEntry_evalsTo
#print axioms LeanNPHardness.MachineComposition.liftScratch_leftTransferEntryCfg_eq_transferStart
#print axioms LeanNPHardness.MachineComposition.compositionProgram_complete_run
#print axioms LeanNPHardness.MachineComposition.compositionProgram_complete_evalsTo
#print axioms LeanNPHardness.MachineComposition.rightPhaseCfg_haltList
#print axioms LeanNPHardness.MachineComposition.compositionMachine_outputs
#print axioms LeanNPHardness.MachineComposition.map_outputAlphabet_invFun_middleAlphabetEquiv
#print axioms LeanNPHardness.MachineComposition.compositionComputable
#print axioms LeanNPHardness.MachineRuntime.stepAux_stack_length_le
#print axioms LeanNPHardness.MachineRuntime.run_stack_length_le
#print axioms LeanNPHardness.MachineRuntime.outputsInTime_output_length_le
#print axioms LeanNPHardness.MachineRuntime.computableInPolyTime_output_length_le
#print axioms LeanNPHardness.MachineRuntime.polynomial_eval_mono
#print axioms LeanNPHardness.MachineComposition.outputSizePolynomial_eval
#print axioms LeanNPHardness.MachineComposition.compositionTimePolynomial_eval
#print axioms LeanNPHardness.MachineComposition.compositionMachine_outputsInTime
#print axioms LeanNPHardness.MachineComposition.compositionComputableInPolyTime
#print axioms LeanNPHardness.PolytimeManyOneReduction.comp
#print axioms LeanNPHardness.PairEncoding.finEncoding
#print axioms LeanNPHardness.PairEncoding.finEncoding_encode_length
#print axioms LeanNPHardness.MachineAdapters.pairSplit_whole_list
#print axioms LeanNPHardness.MachineAdapters.pairSplit_evalsTo
#print axioms LeanNPHardness.MachineAdapters.pairSplit_finEncoding_whole_list
#print axioms LeanNPHardness.UnitEncoding.finEncoding
#print axioms LeanNPHardness.MachineAdapters.ignoreUnitCertificate
#print axioms LeanNPHardness.EncodedLanguage.PolytimeReducesTo
#print axioms LeanNPHardness.EncodedLanguage.InP
#print axioms LeanNPHardness.EncodedLanguage.PolytimeDecider.ofAcceptsIff
#print axioms LeanNPHardness.EncodedLanguage.PolytimeDecider.toInP
#print axioms LeanNPHardness.EncodedLanguage.PolytimeDecider.pullback
#print axioms LeanNPHardness.EncodedLanguage.InP.of_reduction
#print axioms LeanNPHardness.EncodedLanguage.PolytimeVerifier.pullbackCertificateBound
#print axioms LeanNPHardness.EncodedLanguage.PolytimeVerifier.pullbackCertificateBound_eval
#print axioms LeanNPHardness.EncodedLanguage.PolytimeVerifier.pullback_complete
#print axioms LeanNPHardness.EncodedLanguage.PolytimeVerifier.accepts_iff_exists_certificate
#print axioms LeanNPHardness.EncodedLanguage.InNP
#print axioms LeanNPHardness.EncodedLanguage.PolytimeVerifier.toInNP
#print axioms LeanNPHardness.EncodedLanguage.PolytimeDecider.toUnitVerifier
#print axioms LeanNPHardness.EncodedLanguage.inP_toInNP
#print axioms LeanNPHardness.EncodedLanguage.NPHard
#print axioms LeanNPHardness.EncodedLanguage.NPComplete
#print axioms LeanNPHardness.EncodedLanguage.NPHard.of_reduction
#print axioms LeanNPHardness.EncodedLanguage.NPComplete.nphard
#print axioms LeanNPHardness.EncodedLanguage.NPComplete.inNP
#print axioms LeanNPHardness.EncodedLanguage.NPComplete.of_reduction

end LeanNPHardness.Audit
